sfbrigade/datasci-police-budget

documents/userStory.md

Let's edit this together. I created a first pass to get us all thinking.

first pass at user story

---

oaklanddataset/.ipynb_checkpoints/dataexploration-checkpoint.ipynb
oaklanddataset/dataexploration.ipynb

Cleaned up jupyter notebook a bit. Created a dataframe with just total yearly budgets.

totalbudgets

---

components/BalanceBudgetHeader.vue
components/CategoryBreakdown.vue
components/ContactUs.vue
components/event-bus.js
pages/balance-budget.vue
pages/take-action.vue

Hi @jwiederhold ! New to the team, but learning lots from Justine! This branch has a new page created for the "Balance My City's Budget" page - just the background, header, and first pass at the dropdowns (will need to fix coloring to match design). Let me know what you think! thanks

"Balance My City's Budget" page

---

assets/variables.scss
components/Actions.vue
components/BalanceBudgetHeader.vue
components/CityFilter.vue
components/Faq.vue
components/Header.vue
components/TextCard.vue
pages/about.vue
pages/index.vue
pages/see-budget.vue

Also a few text styling refactors/updates

feat: Add skeleton for see-budget page

---

pages/see-budget.vue

I modified the margins on the See Budget page.  The other pages looked OK.

Modified margins on See Budget page

---

components/ContactUs.vue
components/Faq.vue

Note that "data sources" is a TODO -- we need copy for this.

feat: Update homepage FAQ

---

components/CityFilter.vue
components/Header.vue
pages/about.vue
pages/balance-budget.vue
pages/index.vue
pages/see-budget.vue
pages/take-action.vue

I made adjustments to the app's responsiveness.  I also made an adjustment to the navigation drawer so it will extend down the length of the page.

Responsive

---

.eslintrc.js
.gitignore
cypress.json
nuxt.config.js
package.json
test/e2e/integration/index.js
test/e2e/plugins/index.js
test/e2e/support/commands.js
test/e2e/support/index.js
yarn.lock

feat: Add Cypress for e2e tests

---

data/processed/oak_agencies.csv
data/processed/oak_aggregation.csv
package-lock.json
package.json
yarn.lock

data sets added to the processed data folder

processed data sets

---

pages/balance-budget.vue

Replace dummy text with real descriptions for tooltips and make legend circles in-line

---

nuxt.config.js
pages/balance-budget.vue
translations/en-US.js

feat: Add nuxt-i18n translations and refactor balance budget to use them

---

components/BudgetLandingBox.vue
components/DepartmentsWalkthrough.vue
package.json
pages/balance-budget.vue
translations/en-US.js

Uses Vuetify's v-dialog to fix + simplify the overlay code.

fix: Make department copy reactive and refactor landing modal

---

pages/balance-budget.vue
store/budget.js

Enables Kristin to work on importing actual budget amounts from
the data we've sourced using the `updateRealAmounts` mutation.

feat: Add real_amounts to store and refactor budget JS

---

components/DepartmentsWalkthrough.vue
pages/balance-budget.vue
pages/index.vue
store/budget.js

Also round numbers to 2 decimal places

feat: Add remaining copy/buttons to balance budget page

---

components/CityFilter.vue
components/Header.vue
package-lock.json

Quick edit to homepage to incl. links to both see and balance budget, as discussed in wed meeting

Updated homepage text and buttons

---

components/DepartmentsWalkthrough.vue
components/PieChart.vue
pages/balance-budget.vue

feat: Update pie charts to use ChartsJS with tooltips on-hover

---

components/Actions.vue
components/CityFilter.vue
components/Header.vue
mixins/titleMixin.js
pages/about.vue
pages/balance-budget.vue
pages/explore-trends.vue
pages/index.vue
pages/take-action.vue

- Changed browser URL for see-budget to explore-trends
- Changed browser title for all pages, with syntax "[page title] | Police Trends" for each page, e.g., "Home | Police Trends" and "About Us | Police Trends"

Quick changes to browser title and URL

---

components/Faq.vue

Updated text for "where does this data come from" and "upcoming elections".
Need final links for original data sources for city budget data, for both Oakland and SF, to attach as hyperlinks

Slight tweaks to text for home page FAQs

---

pages/explore-trends.vue

toggle use of force levels

---

pages/explore-trends.vue

update sf average budget numbers

---

pages/explore-trends.vue

oakland summary section
